### ISSUE TITLE
Move the "canonical ABI" section to a "diving deeper" section

### ISSUE THREAD

**Issue by rylev** [bytecodealliance/component-docs#112]
Most users of components will never need to consider the existence of the canonical ABI as the concrete mechanism by which components interact with the outside world. While an exploration of this detail of the component model is certainly useful, I think we should place this in a section that is explicitly marked as being only useful for those who want to go beyond just using components.

**Comment by kate-goldenring** [comment]
This aligns with our goal to create an advanced topics section: https://github.com/bytecodealliance/component-docs/issues/10
