### ISSUE TITLE
The keyword `world` should actually be `component`

### ISSUE THREAD

**Issue by J-F-Liu** [bytecodealliance/component-docs#126]
From the document, 

> Roughly, a world describes the contract of a component. Exports are provided by the component, and define what consumers of the component may call; imports are things the component may call.

> A package is a set of interfaces and worlds, potentially defined across multiple files.

If we replace `world` with `component`, all the concepts are much cleaner.

A world means an enviroment that supports running packages. For example there are cli world, http world and gui world.
The gui world can support packages such as canvas, sound, keyboard, mouse etc.

**Comment by vados-cosmonic** [comment]
I think this question has been pretty effectively answered already, but to add some color, the "world" terminology is definitely baked in to the component model at this point (and the [WIT spec](https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT.md) in particular).

An attempt to change this would be more appropriately placed in the [`component-model` repo](https://github.com/WebAssembly/component-model) (there have been [issues raised in the past around naming conventions](https://github.com/WebAssembly/component-model/issues/295)).

**Comment by J-F-Liu** [comment]
Then how about rename `world` to `contract`?

**Comment by vados-cosmonic** [comment]
Yeah @J-F-Liu so we can't decide that here -- you'd need to file an issue against the `component-model` repo.

**Comment by J-F-Liu** [comment]
Convienced myself, thanks.
