### ISSUE TITLE
Incorrect link to the Components page in the Canonical ABI page

### ISSUE THREAD

**Issue by OsamaAhmad00** [bytecodealliance/component-docs#130]
[Here](https://component-model.bytecodealliance.org/advanced/canonical-abi.html), the URL of the `Components` page is set to `https://component-model.bytecodealliance.org/advanced/components.html` instead of `https://component-model.bytecodealliance.org/design/components.html`

**Comment by IFcoltransG** [comment]
I believe this issue can be closed.
