### ISSUE TITLE
Add c# language docs

### ISSUE THREAD

**Issue by kate-goldenring** [bytecodealliance/component-docs#148]
Add C# docs to language guide. Here is an example for C/C++: https://github.com/bytecodealliance/component-docs/pull/147

**Comment by kate-goldenring** [comment]
@rajsite @dicej @bacongobbler tagging in case any of you have interest in taking this on

**Comment by bacongobbler** [comment]
I'd be interested in taking this one on once things have started to stabilize.

**Comment by rajsite** [comment]
A bytecode alliance blogpost went up yesterday on `componentize-dotnet`, [Simplifying components for .NET/C# developers with componentize-dotnet](https://bytecodealliance.org/articles/simplifying-components-for-dotnet-developers-with-componentize-dotnet) which would be a good reference for writing a doc.

**Comment by bacongobbler** [comment]
I followed the blog post as written and ran into an issue. I'm following up with folks on discord. Once I have a working sample, I'll submit a PR.
