### ISSUE TITLE
Update doc to be clear that exported functions work component to component

### ISSUE THREAD

**Issue by jsturtevant** [bytecodealliance/component-docs#176]
The docs state in several places that you must use an interface to exports from other components but this isn't correct. You can compose together two components via an exported function.  I did a prototype here https://github.com/jsturtevant/csharp-components-demos/tree/main/adder-wrapper

https://component-model.bytecodealliance.org/language-support/rust.html#exporting-an-interface-with-cargo-component
```
The sample add.wit file exports a function. However, to use your component from another component, it must export an interface.
```

https://component-model.bytecodealliance.org/language-support/csharp.html#building-a-component-that-exports-an-interface
```
The previous example uses a WIT file that exports a function. However, to use your component from another component, it must export an interface
```

fyi @lukewagner

**Comment by itowlson** [comment]
Thanks.  If memory serves (and that's a big if), this may have been written for a pre-0.2 drop of tools where composing via functions didn't work as well as intended, and copied around / not updated despite more recent tools addressing that issue.  Anyway, agree the statement needs removing!
