### ISSUE TITLE
Renovate host example with latest `wasmtime` and `wasmtime_wasi`

### ISSUE THREAD

**Issue by ifsheldon** [bytecodealliance/component-docs#179]
https://github.com/bytecodealliance/component-docs/tree/main/component-model/examples/example-host

This example is pretty outdated, as it uses `wasmtime` and `wasmtime_wasi` of version `18.0` but the latest is `27.0`. I can try to make a PR to renovate that.

**Comment by kate-goldenring** [comment]
That would be great @ifsheldon
