### ISSUE TITLE
Language Guide: Add (tiny)go

### ISSUE THREAD

**Issue by kate-goldenring** [bytecodealliance/component-docs#37]
Add instructions for compiling go modules and componentizing them. For example:
```sh
tinygo build -target=wasi foo.go
wasm-tools component embed --world myworld ./foo.wit foo.wasm -o foo.embed.wasm
wasm-tools component new -o foo.component.wasm --adapt wasi_snapshot_preview1="$COMPONENT_ADAPTER" foo.embed.wasm
```
where the adapter is built from https://github.com/bytecodealliance/wasmtime/tree/main/crates/wasi-preview1-component-adapter

**Comment by Mossaka** [comment]
I can take a look

**Comment by kate-goldenring** [comment]
@Mossaka i started working on this here https://github.com/bytecodealliance/component-docs/pull/77. would you be willing to give it a review and if its really out of shape we can pivot
