### ISSUE TITLE
Create docs: WIT reference documentation

### ISSUE THREAD

**Issue by kate-goldenring** [bytecodealliance/component-docs#9]
Per [proposed TOC](https://github.com/bytecodealliance/component-docs/pull/1), add section that includes:

More readable version of [the WIT Definition Language doc](https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT.md)

**Comment by lann** [comment]
If its useful, I wrote up a WIT quick ref: https://github.com/lann/wit-quick-ref

**Comment by itowlson** [comment]
I can't assign myself _whee_ but I am working on this.
